table _Measure_CF
	lineageTag: 9fae50eb-0cbb-4574-a73a-7ee9b0070f02

	measure '12_Product_Revenue Score' = ```
			
			VAR _Measure = [TotalRevenue]
			VAR _AllSelectMaxByProduct =
			    SWITCH(TRUE(),
			    ISINSCOPE(T_DimProduct[ProductName]),    
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[ProductName]),
			            "Metric",
			            [TotalRevenue]
			        ),
			    [Metric]
			    ),
			    ISINSCOPE(T_DimProduct[Brand]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[Brand]),
			            "Metric",
			            [TotalRevenue]
			        ),
			        [Metric]
			        ),
			    ISINSCOPE(T_DimProduct[Category]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[Category]),
			            "Metric",
			            [TotalRevenue]
			        ),
			        [Metric]
			        ),
			        ISINSCOPE(T_DimProduct[IsGeneric]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[IsGeneric]),
			            "Metric",
			            [TotalRevenue]
			        ),
			        [Metric]
			        ),
			    BLANK()
			    )
			VAR Score = DIVIDE(_Measure, _AllSelectMaxByProduct,0) * 100
			RETURN  Score
			```
		lineageTag: 501cce19-93f0-4e48-9b40-d68cb7577823

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 13_Rank_Score =
			
			RANK(DENSE, ALLSELECTED(T_DimProduct[Category]), ORDERBY([16_Product_Score], ASC))
		formatString: 0
		lineageTag: 8a9d15b1-0f99-4ecb-b045-2e3ab051d450

	measure '14_Product_Margin Score' = ```
			
			VAR _Measure = [Gross_Profit_Pct]
			VAR _AllSelectMaxByProduct =
			    SWITCH(TRUE(),
			    ISINSCOPE(T_DimProduct[ProductName]),    
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[ProductName]),
			            "Metric",
			            [Gross_Profit_Pct]
			        ),
			    [Metric]
			    ),
			    ISINSCOPE(T_DimProduct[Brand]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[Brand]),
			            "Metric",
			            [Gross_Profit_Pct]
			        ),
			        [Metric]
			        ),
			    ISINSCOPE(T_DimProduct[Category]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[Category]),
			            "Metric",
			            [Gross_Profit_Pct]
			        ),
			        [Metric]
			        ),
			        ISINSCOPE(T_DimProduct[IsGeneric]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[IsGeneric]),
			            "Metric",
			            [Gross_Profit_Pct]
			        ),
			        [Metric]
			        ),
			    BLANK()
			    )
			VAR Score = DIVIDE(_Measure, _AllSelectMaxByProduct,0) * 100
			RETURN  Score
			```
		lineageTag: 82b67e85-a9b8-40c7-ac65-365ac10bcc6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '15_Product_UnitSold Score' = ```
			
			VAR _Measure = [Total_UnitSold]
			VAR _AllSelectMaxByProduct =
			    SWITCH(TRUE(),
			    ISINSCOPE(T_DimProduct[ProductName]),    
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[ProductName]),
			            "Metric",
			            [Total_UnitSold]
			        ),
			    [Metric]
			    ),
			    ISINSCOPE(T_DimProduct[Brand]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[Brand]),
			            "Metric",
			            [Total_UnitSold]
			        ),
			        [Metric]
			        ),
			    ISINSCOPE(T_DimProduct[Category]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[Category]),
			            "Metric",
			            [Total_UnitSold]
			        ),
			        [Metric]
			        ),
			        ISINSCOPE(T_DimProduct[IsGeneric]),
			        MAXX( 
			        SELECTCOLUMNS( 
			            ALLSELECTED(T_DimProduct[IsGeneric]),
			            "Metric",
			            [Total_UnitSold]
			        ),
			        [Metric]
			        ),
			    BLANK()
			    )
			VAR Score = DIVIDE(_Measure, _AllSelectMaxByProduct,0) * 100
			RETURN  Score
			```
		lineageTag: a02f4535-8749-4ed7-9c1e-1b15e353e817

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 16_Product_Score = 0.3* [12_Product_Revenue Score] + 0.4 * [14_Product_Margin Score] + 0.3 * [15_Product_UnitSold Score]
		lineageTag: adb17f0a-7648-43d4-a555-478a6a55b446

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MoM_Metric =
			
			VAR LastMonth = CALCULATE([SelectMetric], DATEADD(T_DimDate[Date], -1, MONTH))
			var CurrentMonth = [SelectMetric]
			RETURN DIVIDE( CurrentMonth - LastMonth, LastMonth, 0)
		lineageTag: 3861829d-5631-4759-89c8-5d9a2f520a82

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 23_MoM_Revenue =
			
			VAR LastMonth = CALCULATE([TotalRevenue], DATEADD(T_DimDate[Date], -1, MONTH))
			VAR CM = [TotalRevenue]
			VAR RESULT = DIVIDE([20_CM_Revenue] - [21_LM_Revenue], [21_LM_Revenue],0)
			RETURN RESULT
		formatString: 0%;-0%;0%
		displayFolder: MoM
		lineageTag: c38a3bd1-dae8-4ab7-aace-f672afb9ef79

	measure 20_CM_Revenue = ```
			
			     CALCULATE( [TotalRevenue] , DATESMTD(T_FactSales[SaleDate]))
			     
			```
		displayFolder: MoM
		lineageTag: 9d0bacb9-4324-48ff-93ad-2a4d7384582b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 21_LM_Revenue =
			
			CALCULATE(
			    TOTALMTD( [TotalRevenue], T_DimDate[Date] ),
			    DATEADD( T_DimDate[Date], -1, MONTH )
			)
		displayFolder: MoM
		lineageTag: 2b3d16d5-8eed-4393-a3db-fdf626d904c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '24_CF_Label Revenue MoM' =
			
			SWITCH(
			    TRUE(),
			    [23_MoM_Revenue] > 0, UNICHAR(9650) & " " & FORMAT([23_MoM_Revenue], "0%"),
			    [23_MoM_Revenue] < 0, UNICHAR(9660) & " " & FORMAT([23_MoM_Revenue], "0%"),
			    "~" & " " & FORMAT([23_MoM_Revenue], "0%")
			)
		displayFolder: MoM
		lineageTag: 3384814f-64eb-462a-b73a-4b50a870ef6c

	measure 'CF_MoM Period' =
			
			VAR _LatestMonth = LOOKUPVALUE( T_DimDate[YearMonth], T_DimDate[Date], MAX(T_FactSales[SaleDate]))
			VAR _LatestName =
			    FORMAT(
			        _LatestMonth,
			        "MMM-YY"
			    )
			VAR _PreviousMonth = LOOKUPVALUE( T_DimDate[YearMonth], T_DimDate[Date], EDATE( MAX(T_FactSales[SaleDate]), -1))
			VAR _PreviousName =
			    FORMAT(
			        _PreviousMonth,
			        "MMM-YY"
			    )
			RETURN "MoM%| "& _LatestName & " vs "& _PreviousName
		displayFolder: MoM
		lineageTag: ace92fa1-0427-495a-8237-b046c6d10b84

	measure 31_MoM_UnitSold =
			
			VAR LastMonth = CALCULATE(totalmtd([Total_Unitsold], T_DimDate[Date]), DATEADD(T_DimDate[Date], -1, MONTH))
			VAR CM = TOTALMTD([Total_Unitsold], T_DimDate[Date])
			VAR RESULT = DIVIDE( CM - LastMonth, LastMonth,0)
			RETURN RESULT
		displayFolder: MoM
		lineageTag: c8d80884-e489-4e06-a56f-51a16d9a80d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '32_CF_Label UnitSold MoM' =
			
			SWITCH(
			    TRUE(),
			    [31_MoM_UnitSold] > 0, UNICHAR(9650) & " " & FORMAT([31_MoM_UnitSold], "0%"),
			    [31_MoM_UnitSold] < 0, UNICHAR(9660) & " " & FORMAT([31_MoM_UnitSold], "0%"),
			    "~" & " " & FORMAT([31_MoM_UnitSold], "0%")
			)
		displayFolder: MoM
		lineageTag: 5d608bc1-3432-44a9-b248-a832db6ee90c

	measure LY_SelectMetric =
			
			CALCULATE([SelectMetric], DATEADD(T_DimDate[Date], -1, YEAR))
		displayFolder: Year
		lineageTag: 0715fead-ac2d-4d5f-9d29-a40ff680e9f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AVGSelectMetric = CALCULATE(AVERAGEX(T_FactSales, [SelectMetric]), ALLSELECTED())
		lineageTag: 9366a2f3-1585-4e48-b6bc-24287bfbf041

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 41_MoM_Margin_perU =
			
			VAR LastMonth = CALCULATE(totalmtd([Margin_perQty],T_DimDate[Date]), DATEADD(T_DimDate[Date], -1, MONTH))
			VAR CM = totalmtd([Margin_perQty],T_DimDate[Date])
			VAR RESULT = DIVIDE( CM - LastMonth, LastMonth,0)
			RETURN RESULT
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: MoM
		lineageTag: 04643721-4934-4234-8c48-748f13a48b91

	measure '42_CF_Label Margin_perU MoM' =
			
			SWITCH(
			    TRUE(),
			    [41_MoM_Margin_perU] > 0, UNICHAR(9650) & " " & FORMAT([41_MoM_Margin_perU], "0%"),
			    [41_MoM_Margin_perU] < 0, UNICHAR(9660) & " " & FORMAT([41_MoM_Margin_perU], "0%"),
			    "~" & " " & FORMAT([31_MoM_UnitSold], "0%")
			)
		displayFolder: MoM
		lineageTag: c7a994e5-d7fb-4dc6-8c36-12ed64fa8089

	measure MetricPct_toTotal = ```
			
			VAR _TotalCategory = CALCULATE([SelectMetric], ALLSELECTED(T_DimProduct[Category]))
			VAR _TotalBrand = CALCULATE([SelectMetric], ALLSELECTED(T_DimProduct[Brand]))
			VAR _TotalCity = CALCULATE([SelectMetric], ALLSELECTED(T_DimPharmacy[City]))
			VAR Result = 
			    DIVIDE( [SelectMetric], 
			        SWITCH(TRUE(),
			             ISINSCOPE( T_DimProduct[Brand]) , _TotalBrand,
			             ISINSCOPE(T_DimProduct[Category]), _TotalCategory,
			             ISINSCOPE(T_DimPharmacy[City]), _TotalCity,
			             CALCULATE([SelectMetric], ALLSELECTED(T_DimProduct[ProductName]))
			        )
			        , 0)
			RETURN Result
			```
		formatString: 0%;-0%;0%
		lineageTag: ebd0dc0f-f3b3-4024-a19e-be86a27e4954

	measure MetricPct_toTotal_format = FORMAT([MetricPct_toTotal], "0%")
		lineageTag: 5773d091-c012-4af7-862f-43083f9368ed

	measure Pie = PieChart.PctOfTotal( [MetricPct_toTotal], [MetricPct_toTotal_format], FALSE(), TRUE(), 10 ,65)
		lineageTag: d00dec55-40a8-4ff8-8f48-067edf1e3f23
		dataCategory: ImageUrl

	measure Cur_Period_Metric =
			
			SWITCH( SELECTEDVALUE(Period[Period]),
			    "W", CALCULATE( [SelectMetric], DATESWTD('Default')),
			    "M", CALCULATE( [SelectMetric], DATESMTD(T_DimDate[Date])),
			    "Q", CALCULATE( [SelectMetric], DATESQTD( T_DimDate[Date])),
			    "Y", CALCULATE([SelectMetric], DATESYTD(T_DimDate[Date])),
			
			    CALCULATE([SelectMetric], DATESYTD(T_DimDate[Date]))
			    )
		displayFolder: comparison
		lineageTag: 05152845-e382-4133-b3ab-f22d4793df36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Previous_Period_Metric = ```
			
			SWITCH( SELECTEDVALUE(Period[Period]),
			    "W", 
			        CALCULATE( [SelectMetric],
			        PREVIOUSWEEK('Default')
			        ),
			    "M", CALCULATE( TOTALMTD( [SelectMetric], T_DimDate[Date]), DATEADD(T_DimDate[Date], -1 , MONTH)),
			    "Q", CALCULATE( TOTALQTD([SelectMetric], T_DimDate[Date]), DATEADD(T_DimDate[Date], -1 , QUARTER)),
			    "Y", CALCULATE( TOTALYTD( [SelectMetric], T_DimDate[Date]), ALL(T_DimDate),DATEADD(T_DimDate[Date], -1 , YEAR)),
			    BLANK()
			    )
			```
		displayFolder: comparison
		lineageTag: 93d0faba-f66e-4fde-b632-0b794959b709

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Metric_Prev_Period_Dum = [Previous_Period_Metric]
		displayFolder: comparison
		lineageTag: 62cf8fde-ea4d-46bb-b502-a18b6fa9375c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Cur_vs_Prev_Period = [Cur_Period_Metric] -[Previous_Period_Metric]
		displayFolder: comparison
		lineageTag: 97c50186-c1af-4fa2-9848-cd37219b3805

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CF_Max_Period =
			
			VAR MaxCurCountry = maxx( ALLSELECTED(T_DimPharmacy[Country]), [Cur_Period_Metric])
			VAR MaxPrevCountry = maxx( ALLSELECTED(T_DimPharmacy[Country]), [Previous_Period_Metric])
			VAR MaxCurCat = maxx(ALLSELECTED(T_DimProduct[Category]), [Cur_Period_Metric])
			VAR MaxPrevCat = maxx( ALLSELECTED(T_DimProduct[Category]), [Previous_Period_Metric])
			
			var result = SWITCH ( TRUE(),
			    SELECTEDVALUE(POV[POV Order]) = 1, MAX( MaxCurCat, MaxPrevCat) * 1.3,
			    SELECTEDVALUE(POV[POV Order]) = 0, max( MaxCurCountry, MaxPrevCountry) * 1.3
			)
			RETURN result
		displayFolder: comparison
		lineageTag: a962059b-1a96-4e1c-9c00-7b812ad93a19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CF_Var_Center =
			
			VAR MaxCurCountry = maxx( ALLSELECTED(T_DimPharmacy[Country]), [Cur_Period_Metric])
			VAR MaxPrevCountry = maxx( ALLSELECTED(T_DimPharmacy[Country]), [Previous_Period_Metric])
			VAR MaxCurCat = maxx(ALLSELECTED(T_DimProduct[Category]), [Cur_Period_Metric])
			VAR MaxPrevCat = maxx( ALLSELECTED(T_DimProduct[Category]), [Previous_Period_Metric])
			
			var result = SWITCH ( TRUE(),
			    SELECTEDVALUE(POV[POV Order]) = 1, MAX( MaxCurCat, MaxPrevCat) * 1.1,
			    SELECTEDVALUE(POV[POV Order]) = 0, max( MaxCurCountry, MaxPrevCountry) * 1.1
			)
			RETURN result
		displayFolder: comparison
		lineageTag: 22a98ceb-9c44-466f-a2d0-5f930af6327b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PctChange_Period =
			
			DIVIDE ( [Cur_Period_Metric] - [Previous_Period_Metric], [Previous_Period_Metric], 0)
		formatString: 0%;-0%;0%
		displayFolder: comparison
		lineageTag: 16bd1fda-ee27-4458-95dd-559473f7ae70

	measure 51_MoM_UnitCost =
			
			VAR LastMonth = CALCULATE(totalmtd([UnitCost_cal], T_DimDate[Date]), DATEADD(T_DimDate[Date], -1, MONTH))
			VAR CM = totalmtd([UnitCost_cal], T_DimDate[Date])
			VAR RESULT = DIVIDE( CM - LastMonth, LastMonth,0)
			RETURN RESULT
		displayFolder: MoM
		lineageTag: 3b8127a7-bf94-474a-adb6-41edefaa8e74

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '52_CF_Label UnitCost MoM' =
			
			SWITCH(
			    TRUE(),
			    [51_MoM_UnitCost] > 0, UNICHAR(9650) & " " & FORMAT([51_MoM_UnitCost], "0%"),
			    [51_MoM_UnitCost] < 0, UNICHAR(9660) & " " & FORMAT([51_MoM_UnitCost], "0%"),
			    "~" & " " & FORMAT([51_MoM_UnitCost], "0%")
			)
		displayFolder: MoM
		lineageTag: ea2c6f46-4f49-435a-b4f2-fb4eba215962

	measure ChangeYoY =
			
			VAR LY = [LY_SelectMetric]
			VAR CY = [SelectMetric]
			VAR YoY = DIVIDE( CY - LY, LY ,0)
			RETURN YoY
		formatString: 0%;-0%;0%
		displayFolder: Year
		lineageTag: f02b069e-7047-43c1-9a92-5a8c4cb43ab2

	column Value
		formatString: 0
		lineageTag: f5eed349-43ca-41c2-be1d-a0834c82e698
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _Measure_CF = calculated
		mode: import
		source = {BLANK()}

	annotation PBI_Id = cc9ce6dc8d9a40089905c06a9c295401

