table T_DimDate
	lineageTag: 158b4d75-6500-4fe4-84ef-8b501ff389ad
	dataCategory: Time

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: e87feaa8-5ea5-4ff7-8577-77bcae7c8309
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: e9ef5d8f-133e-4c37-a611-1da8e5ef1024
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d374d5ce-a681-4e2b-9f64-8f72242d68d9
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: aa2c3316-6d16-4e8c-aa91-8a7200c4dfc5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: b8586014-bba8-4847-b6e8-65e1664f7d89
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4d0bfbbb-430f-4a52-8a91-454ffe588f6f
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: dateTime
		formatString: MMM-YY
		lineageTag: 0b98942d-4d10-4d1d-bebb-f06506e70454
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column WeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 8c772d82-0baa-4594-bea9-e4fb8540d9f7
		summarizeBy: none
		sourceColumn: WeekNumber

		annotation SummarizationSetBy = Automatic

	column Week_Quarter =
			
			VAR CurrentQuarter = QUARTER([Date])
			VAR CurrentYear = YEAR([Date])
			VAR FirstDayOfQuarter = DATE(CurrentYear, (CurrentQuarter - 1) * 3 + 1, 1)
			VAR DaysSinceQtrStart = [Date] - FirstDayOfQuarter
			VAR WeekNumOfQtr = ROUNDUP( DaysSinceQtrStart / 7, 0) + 1
			RETURN
			FORMAT(WeekNumOfQtr, "00")
		lineageTag: e0126b58-2a80-4b4f-b550-874acc96bccc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column YearQ = "Q"&T_DimDate[Quarter] & "-" & RIGHT(T_DimDate[Year],2)
		lineageTag: 852dc495-baea-4c64-ae78-9cfe9864724d
		summarizeBy: none
		sortByColumn: QuarterYSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column QuarterYSort
		dataType: double
		lineageTag: 1705b04a-97f6-42db-8de5-34d2c892c0ef
		summarizeBy: none
		sourceColumn: QuarterYSort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearWeek
		dataType: double
		lineageTag: 64290a7b-c438-4c97-aeb6-d0dd7e344755
		summarizeBy: none
		sourceColumn: YearWeek

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition T_DimDate = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Thien.Dao\OneDrive - Techtronic Industries Co. Ltd\THIENDAO\PBI\reference\FP20\DataDNA-Pharma-Data-202601\Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    T_DimDate_Table = Source{[Item="T_DimDate",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_DimDate_Table,{{"DateKey", Int64.Type}, {"Date", type date}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"YearMonth", type date}}),
				    #"Inserted Week of Year" = Table.AddColumn(#"Changed Type", "WeekNumber", each Date.WeekOfYear([Date]), Int64.Type),
				    #"Inserted Last Characters" = Table.AddColumn(#"Inserted Week of Year", "QuarterYSort", each  Number.From(Text.End( Text.From([Year]), 2)) *100 + [Quarter], type number),
				    #"Added Custom" = Table.AddColumn(#"Inserted Last Characters", "YearWeek", each Number.From(Text.End( Text.From([Year]), 2)) *100 + [WeekNumber], type number)
				in
				    #"Added Custom"

	calendar Default
		lineageTag: 81902829-44a9-45c9-adcf-08dd910bb105

		calendarColumnGroup = year
			primaryColumn: Year

		calendarColumnGroup = quarter
			primaryColumn: YearQ

		calendarColumnGroup = month
			primaryColumn: YearMonth

		calendarColumnGroup = week
			primaryColumn: YearWeek

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

