table T_DimProduct
	lineageTag: cd56c0b8-e6f4-4c04-bece-487df4870a02

	column ProductID
		dataType: string
		lineageTag: 3690e419-ac45-4487-a41e-583b283c58d7
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 4baa5013-bbeb-4e2a-8560-b7260b447e45
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: e98df0a3-f469-4524-9778-9ca80e2b67e2
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: a9829f17-6bc0-46d3-867f-55394edf3474
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column IsGeneric
		dataType: string
		lineageTag: a42c8d3b-43f0-4857-8c60-6c1f7e8c757d
		summarizeBy: none
		sourceColumn: IsGeneric

		annotation SummarizationSetBy = Automatic

	column PackSize
		dataType: string
		lineageTag: ab9bcdf4-3960-4369-8ba5-36d95a1106d4
		summarizeBy: none
		sourceColumn: PackSize

		annotation SummarizationSetBy = Automatic

	column ListPriceEUR
		dataType: double
		lineageTag: 8fed84f3-65ca-4a44-bde1-37a09683a909
		summarizeBy: none
		sourceColumn: ListPriceEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StandardCostEUR
		dataType: double
		lineageTag: 21d45c6d-2fdd-4da5-b867-9f84c128f1db
		summarizeBy: none
		sourceColumn: StandardCostEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LaunchDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a99bea27-317b-4b8e-836c-2aeca3f09f3f
		summarizeBy: none
		sourceColumn: LaunchDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsDiscontinued
		dataType: string
		lineageTag: cc78590c-a0f9-4970-8c97-f75d9b7bfbe7
		summarizeBy: none
		sourceColumn: IsDiscontinued

		annotation SummarizationSetBy = Automatic

	column DiscontinuedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c42d9968-8cc5-476a-bdb0-36dda53d7806
		summarizeBy: none
		sourceColumn: DiscontinuedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition T_DimProduct = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Thien.Dao\OneDrive - Techtronic Industries Co. Ltd\THIENDAO\PBI\reference\FP20\DataDNA-Pharma-Data-202601\Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    T_DimProduct_Table = Source{[Item="T_DimProduct",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_DimProduct_Table,{{"ProductID", type text}, {"ProductName", type text}, {"Category", type text}, {"Brand", type text}, {"IsGeneric", type text}, {"PackSize", type text}, {"ListPriceEUR", type number}, {"StandardCostEUR", type number}, {"LaunchDate", type date}, {"IsDiscontinued", type text}, {"DiscontinuedDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

