table T_FactSales
	lineageTag: 03a73bbd-b4d3-4fc7-901a-d946c1f561b7

	column SalesID
		dataType: string
		lineageTag: 97a088cb-e207-4f79-b429-197ce59b5296
		summarizeBy: none
		sourceColumn: SalesID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 240338af-246d-4792-9606-bb163cb0a4b5
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column PharmacyID
		dataType: string
		lineageTag: dc2c5745-c7b5-47e6-9d44-0c7af49f131a
		summarizeBy: none
		sourceColumn: PharmacyID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: bf013b47-1ce7-4086-a43e-1ed3fdd3c7c6
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column UnitsSold
		dataType: int64
		formatString: 0
		lineageTag: 5bea19a5-0b00-451f-934d-a5e08646b839
		summarizeBy: sum
		sourceColumn: UnitsSold

		annotation SummarizationSetBy = Automatic

	column RevenueEUR
		dataType: double
		lineageTag: 4bb984cc-9fd0-4c06-b13a-4177c9f07030
		summarizeBy: sum
		sourceColumn: RevenueEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostEUR
		dataType: double
		lineageTag: cb13b8cb-88f5-4495-9240-5073f450421d
		summarizeBy: sum
		sourceColumn: CostEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MarginEUR
		dataType: double
		formatString: 0
		lineageTag: 43d4562e-a20a-417e-b07e-cff3a57987f4
		summarizeBy: sum
		sourceColumn: MarginEUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column PromoFlag
		dataType: string
		lineageTag: 8075d753-4956-4002-b1a4-e864f449496e
		summarizeBy: none
		sourceColumn: PromoFlag

		annotation SummarizationSetBy = Automatic

	column SaleDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f91a806a-16d6-4b4a-b6a4-960d9682d9c3
		summarizeBy: none
		sourceColumn: SaleDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition T_FactSales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Thien.Dao\OneDrive - Techtronic Industries Co. Ltd\THIENDAO\PBI\reference\FP20\DataDNA-Pharma-Data-202601\Pharmacy_Data_Challenge_Dataset.xlsx"), null, true),
				    T_FactSales_Table = Source{[Item="T_FactSales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(T_FactSales_Table,{{"SalesID", type text}, {"DateKey", Int64.Type}, {"PharmacyID", type text}, {"ProductID", type text}, {"UnitsSold", Int64.Type}, {"RevenueEUR", type number}, {"CostEUR", type number}, {"MarginEUR", type number}, {"PromoFlag", type text}}),
				    #"Inserted Date" = Table.AddColumn(#"Changed Type", "SaleDate", each Date.From(Text.From([DateKey], "en-US")), type date)
				in
				    #"Inserted Date"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

